name: eodc-dask
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.12
  - dask-gateway<=2024.5.2
  - dask<=2024.5.2      
  - rioxarray=0.17.0
  - odc-stac=0.3.10
  - zarr=2.18.4
  - bokeh=3.6.3
  - stactools=0.5.3
  - pystac-client=0.8.6
  - pyproj=3.7.0
  - s3fs=2025.2.0
  - fsspec=2025.2.0
  - jinja2>=3.1.6
  - matplotlib=3.10.3
  - rich=14.0.0
  - cytoolz=1.0.1
  - h11=0.16.0
  - ipykernel>=6.29
  - pip
  - pip:
    - lz4==4.4.3
    - msgpack==1.1.0 
    - pytileproj
    - eodc==2025.6.1